import { WaitlistForm } from "./_components/waitlist-form";

export default function Home() {
  const demoUrl = process.env.DEMO_AUDIO_URL?.trim() || "";

  return (
    <main className="mx-auto flex min-h-screen max-w-3xl flex-col gap-16 px-6 py-20 font-mono">
      <section className="flex flex-col gap-6">
        <p className="text-xs uppercase tracking-[0.2em] text-neutral-500">
          kst-music · private alpha
        </p>
        <h1 className="text-4xl font-semibold tracking-tight md:text-5xl">
          AI music making that doesn&apos;t feel like magic homework.
        </h1>
        <p className="max-w-2xl text-base text-neutral-700 dark:text-neutral-300">
          A tiny, opinionated music tool for producers. Write a prompt, get a
          stem. Demystifying AI-generated music and sample creation — without
          the eight-step prompt stack or the Discord onboarding quiz.
        </p>
      </section>

      <section className="flex flex-col gap-3 rounded-xl border border-neutral-200 bg-neutral-50 p-5 dark:border-neutral-800 dark:bg-neutral-900/40">
        <div className="flex items-baseline justify-between">
          <h2 className="text-sm font-semibold uppercase tracking-wider text-neutral-600 dark:text-neutral-300">
            Hear a 15-second clip
          </h2>
          <span className="text-xs text-neutral-500">
            prompt: lofi jazz guitar, dusty vinyl
          </span>
        </div>
        {demoUrl ? (
          <audio
            controls
            src={demoUrl}
            preload="metadata"
            className="w-full"
            aria-label="Demo clip generated by kst-music"
          />
        ) : (
          <div className="flex h-12 items-center rounded bg-neutral-200/60 px-3 text-xs text-neutral-500 dark:bg-neutral-800/60">
            Demo clip uploading. Check back in a minute.
          </div>
        )}
        <p className="text-xs text-neutral-500">
          Generated via Replicate <code>meta/musicgen</code>, stored in Vercel
          Blob. Your clips will be yours — cached and downloadable.
        </p>
      </section>

      <section className="flex flex-col gap-4">
        <h2 className="text-xl font-semibold tracking-tight">
          Join the waitlist
        </h2>
        <p className="max-w-xl text-sm text-neutral-700 dark:text-neutral-300">
          Drop your email. We&apos;re hand-seating the first batch of producers
          with invite codes — 10 clips each, no credit card. Expect a message
          within a week or two.
        </p>
        <WaitlistForm />
      </section>

      <footer className="mt-auto border-t border-neutral-200 pt-6 text-xs text-neutral-500 dark:border-neutral-800">
        <p>
          <a className="underline" href="/generate">
            /generate
          </a>{" "}
          · internal alpha ·{" "}
          <a className="underline" href="/api/hello">
            /api/hello
          </a>
        </p>
      </footer>
    </main>
  );
}
